# this file is part of hapidock
# refer https://jjude.com/hapidock

# refer https://github.com/docker-library/docs/tree/master/postgres
# for more info about usage 
FROM postgres:alpine

MAINTAINER Joseph Jude

CMD ["postgres"]

EXPOSE 5432
